### ISSUE TITLE
Ini file issue

### ISSUE THREAD

**Issue by Zolrex** [Northfear/Vanilla-Conquer-vita#7]
2) engine not create [Vita] and [Video] sections,manually not sure at which line or where exactly in ini those sections should be created to work.
1) In description is said to change cursor speed use "ControllerPointerSpeed" under Vita section. i created Vita section(video setting is work there in this section)manually,and add this line to speed-up cursor speed,tried ControllerPointerSpeed=5-10-20-200 but cursor speed still remain default one.

Still awesome port just like other ones from you,thanks! wish there would be possible to reduce resolution a bit with fullscreen option,to make units a bit bigger on screen(or like in Dune legacy zoom method).

**Comment by Northfear** [comment]
I'll probably update all of my ports soon, so I'll look into it when I get a chance

**Comment by Zolrex** [comment]
> I'll probably update all of my ports soon, so I'll look into it when I get a chance

That would be awesome,your ports are so good,to play those games on portable vita device is great experience (openxcom,dune,red alert-tiberian,and new fallout port with other ports) thanks for your work! )

**Comment by Northfear** [comment]
1. You should exit the game with "Exit Game" button in order to create the default ini file.
2. ControllerPointerSpeed is in the [Mouse] section (Fixed the readme)

DOS mode with lower resolution should be supported in theory by Vanilla Conquer, but I'm a bit short of free time to test/add it's support in Vita port. 640x400 is the only supported resolution right now.
